Repository codedevlalit/LeadCommerce, pull requests merged in 2025-01, with the labels that each got.

#6 product list UI
  angular.json
  src/app/home/home.component.html
  src/app/product-list/product-list.component.html
  src/app/product-list/product-list.component.ts
  src/assets/images/TargetWall.jpeg
Labels: enhancement

#7 home page addition
  src/app/app.component.html
  src/app/app.component.ts
  src/app/home/home.component.html
  src/app/shared/footer/footer.component.css
  src/app/shared/footer/footer.component.html
  src/app/shared/footer/footer.component.spec.ts
  src/app/shared/footer/footer.component.ts
  src/app/shared/header/header.component.css
  src/app/shared/header/header.component.html
  src/app/shared/header/header.component.spec.ts
  src/app/shared/header/header.component.ts
Labels: enhancement

#10 Anchor linking
  src/app/home/home.component.html
Labels: enhancement

#12 add about us page.
  README.md
  angular.json
  src/app/about-us/about-us.component.css
  src/app/about-us/about-us.component.html
  src/app/about-us/about-us.component.spec.ts
  src/app/about-us/about-us.component.ts
  src/app/app.routes.ts
  src/app/shared/header/header.component.html
Labels: enhancement

#14 resolve button alignment issue
  README.md
  src/app/shared/header/header.component.css
  src/app/shared/header/header.component.html
Labels: bug, good first issue

#16 15 set routing for smartphone laptop and clothes
  src/app/app.routes.ts
  src/app/product-list/product-list.component.html
  src/app/product-list/product-list.component.ts
  src/app/shared/header/header.component.html
  src/app/shared/header/header.component.ts
Labels: enhancement

#18 #17 navigation of header
  README.md
  src/app/product-list/product-list.component.ts
Labels: bug, good first issue

#20 #19 create product page
  src/app/app.routes.ts
  src/app/product-list/product-list.component.css
  src/app/product-list/product-list.component.html
  src/app/product-list/product-list.component.ts
  src/app/product/product.component.css
  src/app/product/product.component.html
  src/app/product/product.component.spec.ts
  src/app/product/product.component.ts
Labels: enhancement

#22 policy page added
  src/app/privacy-policy/privacy-policy.component.css
  src/app/privacy-policy/privacy-policy.component.html
  src/app/privacy-policy/privacy-policy.component.spec.ts
  src/app/privacy-policy/privacy-policy.component.ts
Labels: enhancement

#24 setup ng icons
  package-lock.json
  package.json
  src/app/shared/header/header.component.html
  src/app/shared/header/header.component.ts
  src/styles.css
Labels: enhancement

#27 Sample static cart detail page added to the flow
  src/app/app.routes.ts
  src/app/cart/cart.component.css
  src/app/cart/cart.component.html
  src/app/cart/cart.component.spec.ts
  src/app/cart/cart.component.ts
  src/app/shared/header/header.component.html
Labels: enhancement

#33 icon position changed
  src/app/shared/header/header.component.html
Labels: bug

#32 improve-design-for-cart-page
  src/app/cart/cart.component.css
  src/app/cart/cart.component.html
  src/app/product/product.component.html
Labels: enhancement

#35 login icon added
  src/app/shared/header/header.component.html
  src/app/shared/header/header.component.ts
Labels: enhancement

#45 add order history page
  src/app/app.routes.ts
  src/app/orders/orders.component.css
  src/app/orders/orders.component.html
  src/app/orders/orders.component.spec.ts
  src/app/orders/orders.component.ts
  src/app/shared/header/header.component.html
  src/app/shared/header/header.component.ts
Labels: enhancement

#43 #42-change-about-us-page-navigation-location
  src/app/shared/footer/footer.component.html
  src/app/shared/header/header.component.css
  src/app/shared/header/header.component.html
Labels: bug

#41 #40-create-forget-password-and-sign-up-page
  src/app/app.routes.ts
  src/app/authentication/forget-password/forget-password.component.css
  src/app/authentication/forget-password/forget-password.component.html
  src/app/authentication/forget-password/forget-password.component.spec.ts
  src/app/authentication/forget-password/forget-password.component.ts
  src/app/authentication/signup/signup.component.css
  src/app/authentication/signup/signup.component.html
  src/app/authentication/signup/signup.component.spec.ts
  src/app/authentication/signup/signup.component.ts
Labels: enhancement

#46 login page added
  src/app/app.routes.ts
  src/app/authentication/login/login.component.css
  src/app/authentication/login/login.component.html
  src/app/authentication/login/login.component.spec.ts
  src/app/authentication/login/login.component.ts
  src/app/shared/header/header.component.html
Labels: enhancement

#48 login - email and phone difference logic implementation
  src/app/app.routes.ts
  src/app/authentication/login/login.component.html
  src/app/authentication/login/login.component.ts
  src/app/core/utilities/common.functions.ts
Labels: enhancement, help wanted

#50 #49-login-to-home-page-navigation
  src/app/authentication/login/login.component.html
  src/app/authentication/login/login.component.ts
Labels: enhancement

#52 auth service
  src/app/authentication/signup/signup.component.css
  src/app/authentication/signup/signup.component.html
  src/app/models/user.ts
  src/app/service/authentication.service.spec.ts
  src/app/service/authentication.service.ts
Labels: enhancement

#54 #53-change-counter-of-header-cart-item
  src/app/product/product.component.html
  src/app/product/product.component.ts
  src/app/service/cart.service.spec.ts
  src/app/service/cart.service.ts
  src/app/shared/header/header.component.html
  src/app/shared/header/header.component.ts
Labels: enhancement
